This is my test file for this exception